// Comprehensive list of college degree programs available in the Philippines.
// Used by the admissions form's searchable course dropdown.
export const PROGRAM_COURSES: string[] = [
  // Criminology / Law
  "Bachelor of Science in Criminology",
  "Bachelor of Laws (LLB)",
  "Juris Doctor (JD)",
  // Education
  "Bachelor of Early Childhood Education",
  "Bachelor of Elementary Education",
  "Bachelor of Secondary Education",
  "Bachelor of Special Needs Education",
  "Bachelor of Physical Education",
  "Bachelor of Technology and Livelihood Education",
  "Bachelor of Culture and Arts Education",
  // Nursing / Allied Health
  "Bachelor of Science in Nursing",
  "Bachelor of Science in Midwifery",
  "Bachelor of Science in Medical Technology",
  "Bachelor of Science in Pharmacy",
  "Bachelor of Science in Physical Therapy",
  "Bachelor of Science in Occupational Therapy",
  "Bachelor of Science in Radiologic Technology",
  "Bachelor of Science in Respiratory Therapy",
  "Bachelor of Science in Nutrition and Dietetics",
  "Bachelor of Science in Public Health",
  // Medicine / Dentistry (graduate)
  "Doctor of Medicine (MD)",
  "Doctor of Dental Medicine (DMD)",
  // IT / Computing
  "Bachelor of Science in Information Technology",
  "Bachelor of Science in Computer Science",
  "Bachelor of Science in Information Systems",
  "Bachelor of Science in Software Engineering",
  "Bachelor of Science in Data Science",
  "Bachelor of Science in Computer Engineering",
  // Engineering / Architecture
  "Bachelor of Science in Civil Engineering",
  "Bachelor of Science in Mechanical Engineering",
  "Bachelor of Science in Electrical Engineering",
  "Bachelor of Science in Electronics Engineering",
  "Bachelor of Science in Industrial Engineering",
  "Bachelor of Science in Chemical Engineering",
  "Bachelor of Science in Sanitary Engineering",
  "Bachelor of Science in Mining Engineering",
  "Bachelor of Science in Geodetic Engineering",
  "Bachelor of Science in Agricultural Engineering",
  "Bachelor of Science in Architecture",
  // Business / Accountancy
  "Bachelor of Science in Accountancy",
  "Bachelor of Science in Accounting Technology",
  "Bachelor of Science in Management Accounting",
  "Bachelor of Science in Business Administration",
  "Bachelor of Science in Entrepreneurship",
  "Bachelor of Science in Marketing Management",
  "Bachelor of Science in Financial Management",
  "Bachelor of Science in Human Resource Management",
  "Bachelor of Science in Operations Management",
  "Bachelor of Science in Business Economics",
  "Bachelor of Science in Customs Administration",
  "Bachelor of Science in Office Administration",
  "Bachelor of Science in Real Estate Management",
  // Hospitality / Tourism
  "Bachelor of Science in Hospitality Management",
  "Bachelor of Science in Hotel and Restaurant Management",
  "Bachelor of Science in Tourism Management",
  "Bachelor of Science in Travel Management",
  // Social Sciences / Humanities / Arts
  "Bachelor of Arts in Political Science",
  "Bachelor of Arts in Psychology",
  "Bachelor of Science in Psychology",
  "Bachelor of Arts in Communication",
  "Bachelor of Arts in English",
  "Bachelor of Arts in Filipino",
  "Bachelor of Arts in History",
  "Bachelor of Arts in Philosophy",
  "Bachelor of Arts in Sociology",
  "Bachelor of Arts in Anthropology",
  "Bachelor of Arts in Economics",
  "Bachelor of Arts in Asian Studies",
  "Bachelor of Arts in International Studies",
  "Bachelor of Arts in Theater Arts",
  "Bachelor of Music",
  "Bachelor of Fine Arts",
  // Sciences
  "Bachelor of Science in Biology",
  "Bachelor of Science in Chemistry",
  "Bachelor of Science in Physics",
  "Bachelor of Science in Mathematics",
  "Bachelor of Science in Statistics",
  "Bachelor of Science in Environmental Science",
  "Bachelor of Science in Marine Biology",
  "Bachelor of Science in Geology",
  // Agriculture / Fisheries / Forestry
  "Bachelor of Science in Agriculture",
  "Bachelor of Science in Fisheries",
  "Bachelor of Science in Forestry",
  "Bachelor of Science in Agribusiness",
  "Bachelor of Science in Agricultural Economics",
  // Public Service / Maritime / Aviation
  "Bachelor of Science in Social Work",
  "Bachelor of Science in Marine Engineering",
  "Bachelor of Science in Marine Transportation",
  "Bachelor of Science in Aviation",
  "Bachelor of Science in Aircraft Maintenance Technology",
  // Others
  "Associate in Computer Technology",
  "Associate in Office Administration",
];
